# Generated by Django 4.1.5 on 2023-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0005_alter_car_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Pin',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
